### ISSUE TITLE
Unloading MB-Lab from add-on menu in Blender gives an Exception in module unregister()

### ISSUE THREAD

**Issue by NumesSanguis** [animate1978/MB-Lab#101]
**Describe the bug**
Unloading MB-Lab from add-on menu in Blender gives an `Exception in module unregister()`.

**To Reproduce**
1. Edit --> Preferences --> Add-ons --> Install... --> something like "MB-Lab-1-7-3.zip"
2. Check box for "Characters MB-Lab"
3. Save preferences and close window
4. Edit --> Preferences --> Add-ons --> uncheck "Characters MB-Lab"

**Expected behavior**
Expect no error, but got error message.

**System**
- Ubuntu 16.04
- blender-2.80-a070815d127e-linux-glibc224-x86_64
- MB-Lab v1.7.3 (2018-03-05)

**Logs**

    Exception in module unregister(): '/home/*user*/.config/blender/2.80/scripts/addons/MB-Lab-master/__init__.py'
    Traceback (most recent call last):
      File "/home/*user*/Downloads/blender-2.80-a070815d127e-linux-glibc224-x86_64/2.80/scripts/modules/addon_utils.py", line 446, in disable
        mod.unregister()
      File "/home/*user*/.config/blender/2.80/scripts/addons/MB-Lab-master/__init__.py", line 2305, in unregister
        addon_updater_ops.unregister()
      File "/home/*user*/.config/blender/2.80/scripts/addons/MB-Lab-master/addon_updater_ops.py", line 1418, in unregister
        bpy.utils.unregister_class(cls)
    RuntimeError: unregister_class(...):, missing bl_rna attribute from 'RNAMeta' instance (may not be registered)

    Error: Traceback (most recent call last):
      File "/home/*user*/Downloads/blender-2.80-a070815d127e-linux-glibc224-x86_64/2.80/scripts/modules/addon_utils.py", line 446, in disable
        mod.unregister()
      File "/home/*user*/.config/blender/2.80/scripts/addons/MB-Lab-master/__init__.py", line 2305, in unregister
        addon_updater_ops.unregister()
      File "/home/*user*/.config/blender/2.80/scripts/addons/MB-Lab-master/addon_updater_ops.py", line 1418, in unregister
        bpy.utils.unregister_class(cls)
    RuntimeError: unregister_class(...):, missing bl_rna attribute from 'RNAMeta' instance (may not be registered)

**Comment by animate1978** [comment]
This issue was present before, during the development of the updater for MB-Lab, though I don't think anyone tested it out until now.

https://github.com/animate1978/MB-Lab/issues/89#issuecomment-466789849

**Comment by telnetr4** [comment]
@NumesSanguis I believe this got fixed in master since this issue was raised. I just tried the steps to reproduce and I didnt get any unregister errors.

**Comment by animate1978** [comment]
This really needs to be looked at. I myself have looked at the code but nothing is 'clicking', I am confused

**Comment by mreloaded** [comment]
Pull request with a possible fix - https://github.com/animate1978/MB-Lab/pull/135

**Comment by animate1978** [comment]
This issue is finally worked out, thank you mreloaded for your fix!
