### ISSUE TITLE
Wrong menu sub-panel drawing (sub-panel contains following parent buttons)

### ISSUE THREAD

**Issue by mklemarczyk** [animate1978/MB-Lab#173]
**Describe the bug**
Menu drawing errors. The toolbox menu is drawn in wrong sections.
Example: Opened new Blender without any project have correct menu if all sections opened. Opening "Face Expressions" disable buttons below, that should be still available like for example "Assets library".  

**To Reproduce**
1. Open Blender
2. Install and enable MB-Lab addon
3. Open MB-Lab toolbox
4. Open "Face Expression" section
5. Unable to open "Assets library" section (due to disabled controls)

**Expected behavior**
Able to open "Assets library" section

**Screenshots**
![menu_bad1_LI](https://user-images.githubusercontent.com/2727261/68075824-93104f80-fdad-11e9-998e-60af4374be11.jpg)
![menu_bad2_LI](https://user-images.githubusercontent.com/2727261/68075826-96a3d680-fdad-11e9-80ac-b9622c973c9e.jpg)

**Additional context**
The opened section panel contains expand/collapse buttons, it should not contain them.

**Logs**
Blender version 2.80.75
MB-Lab version 1.7.6

**Comment by mklemarczyk** [comment]
The PR #176 contains cleanup and fix for the problem.

**Comment by mklemarczyk** [comment]
Fix introduced bug after wrong merge with feature Humanoid Rotations.
I'm working on it. Do you know what is progress on that feature?

**Comment by animate1978** [comment]
Not at all, I assumed incorrectly if it was functioning

**Comment by mklemarczyk** [comment]
According to log. It is not the fix that introduced problem.

Problem is missing import in algorithms.py:
```
C:\Users\mklem\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\MB-Lab-1_7_6\__init__.py:2000
Traceback (most recent call last):
  File "C:\Users\mklem\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\MB-Lab-1_7_6\__init__.py", line 2008, in draw
    mblab_shapekeys.update_expressions_data()
  File "C:\Users\mklem\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\MB-Lab-1_7_6\animationengine.py", line 1497, in update_expressions_data
    self.identify_model_type()
  File "C:\Users\mklem\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\MB-Lab-1_7_6\animationengine.py", line 1427, in identify_model_type
    obj = algorithms.get_active_body()
  File "C:\Users\mklem\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\MB-Lab-1_7_6\algorithms.py", line 724, in get_active_body
    obj_id = get_template_model(c_obj)
  File "C:\Users\mklem\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\MB-Lab-1_7_6\algorithms.py", line 698, in get_template_model
    template = identify_template(obj)
  File "C:\Users\mklem\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\MB-Lab-1_7_6\algorithms.py", line 686, in identify_template
    config_data = get_configuration()
NameError: name 'get_configuration' is not defined
```

**Comment by mklemarczyk** [comment]
I will update algorithms.py within the branch of the menus and create new PR.

**Comment by mklemarczyk** [comment]
PR #178 created to address minor menu adjustments and import error in algorithms.py.

**Comment by mklemarczyk** [comment]
@all Please cross-check if the problem is resolved. It is fixed in my Blender.
Once confirmed, it can be closed. 😄
