### ISSUE TITLE
Anime Characters Broken

### ISSUE THREAD

**Issue by animate1978** [animate1978/MB-Lab#21]
```
Traceback (most recent call last):
  File "/home/farishta/.config/blender/2.80/scripts/addons/MB-Lab/__init__.py", line 1726, in execute
    start_lab_session()
  File "/home/farishta/.config/blender/2.80/scripts/addons/MB-Lab/__init__.py", line 101, in start_lab_session
    mblab_humanoid.init_database(obj,character_identifier,rigging_type)
  File "/home/farishta/.config/blender/2.80/scripts/addons/MB-Lab/humanoid.py", line 217, in init_database
    self.mat_engine = materialengine.MaterialEngine(self.obj_name, self.characters_config[character_identifier])
  File "/home/farishta/.config/blender/2.80/scripts/addons/MB-Lab/materialengine.py", line 33, in __init__
    self.image_specular_file = character_config["texture_specular"]
KeyError: 'texture_specular'

```

![screenshot_2018-12-30_10-11-25](https://user-images.githubusercontent.com/479115/50549013-70f0f280-0c1b-11e9-81fd-d871eb33382d.png)

To be fair, I haven't paid any attention to the anime characters, in 2.79 they seem to build fine but in 2.80 the above happens, so this needs to be addressed.

**Comment by animate1978** [comment]
![screenshot_2018-12-30_10-34-01](https://user-images.githubusercontent.com/479115/50549207-89aed780-0c1e-11e9-9679-8415067aa0ba.png)

Went to Blender 2.79 to try to see if the problem existed before and got the exact same result so this has been a problem since then.

**Comment by animate1978** [comment]
This bug also causes MB-Lab to stay in Creation mode, preventing users from editing the anime character from MB-Lab.

Also does not import the lighting setup.

**Comment by animate1978** [comment]
Tested ManuelBastioniLAB 1.6.1. Anime character setup runs perfectly fine, so I broke something somewhere in regards to this...

**Comment by animate1978** [comment]
Bug was in the characters_config.json file, it was looking for additional textures but could not find them. That is fixed now.
