### ISSUE TITLE
VGroups Creator bug

### ISSUE THREAD

**Issue by animate1978** [animate1978/MB-Lab#273]
https://github.com/animate1978/MB-Lab/blob/fb74b1f52194945d7f8b08fbddb3fc85df7577ed/vgroupscreator.py#L173

Trying to test the new tools, unsure if this is a bug or a user error
```

Error: Traceback (most recent call last):
  File "/home/farishta/.config/blender/2.82/scripts/addons/MB-Lab/__init__.py", line 6543, in execute
    vgroupscreator.save_current_vgroups_type('BASE')
  File "/home/farishta/.config/blender/2.82/scripts/addons/MB-Lab/vgroupscreator.py", line 173, in save_current_vgroups_type
    file_name)
NameError: name 'file_name' is not defined

location: <unknown location>:-1


```

**Comment by TetoTheSquirrelFox** [comment]
My bad, I changed things and didn't test them.
have to change file_name by current_vgroups_file
Bug fixed.
