### ISSUE TITLE
i cant finalize  

### ISSUE THREAD

**Issue by max1341** [animate1978/MB-Lab#336]
i have this problem when i hit finalize blender say this   

Python: Traceback (most recent call last):
  File "C:\Users\sajjad abwbaker\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\MB-Lab\__init__.py", line 1329, in execute
    mblab_humanoid.set_rest_pose()
  File "C:\Users\sajjad abwbaker\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\MB-Lab\humanoid.py", line 1194, in set_rest_pose
    self.sk_engine.apply_armature_modifier()
  File "C:\Users\sajjad abwbaker\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\MB-Lab\skeletonengine.py", line 119, in apply_armature_modifier
    algorithms.apply_modifier(obj, armature_modifier)
  File "C:\Users\sajjad abwbaker\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\MB-Lab\algorithms.py", line 1142, in apply_modifier
    bpy.ops.object.modifier_apply(apply_as='DATA', modifier=modifier_name)
  File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\scripts\modules\bpy\ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
TypeError: Converting py args to operator properties: : keyword "apply_as" unrecognized

location: <unknown location>:-1

i have no clue what is this i have never used python plz help

**Comment by Upliner** [comment]
You need MB-Lab version 1.7.8.5 to work in Blender 2.91

**Comment by max1341** [comment]
> You need MB-Lab version 1.7.8.5 to work in Blender 2.91

thx that fixed it
