### ISSUE TITLE
Create character -> IndexError: list index out of range

### ISSUE THREAD

**Issue by jaggzh** [animate1978/MB-Lab#338]
I have one sort-of-finalized character (1.7.7 was erroring on finalize).
When creating a new character, with 1.7.8, I get:

```Python: Traceback (most recent call last):
  File "/home/jaggz/.config/blender/2.91/scripts/addons/MB-Lab/__init__.py", line 2492, in execute
    start_lab_session()
  File "/home/jaggz/.config/blender/2.91/scripts/addons/MB-Lab/__init__.py", line 159, in start_lab_session
    mblab_humanoid.init_database(obj, character_identifier, rigging_type)
  File "/home/jaggz/.config/blender/2.91/scripts/addons/MB-Lab/humanoid.py", line 276, in init_database
    self.morph_engine = morphengine.MorphingEngine(self.obj_name, self.characters_config[character_identifier])
  File "/home/jaggz/.config/blender/2.91/scripts/addons/MB-Lab/morphengine.py", line 157, in __init__
    self.measures = self.calculate_measures()
  File "/home/jaggz/.config/blender/2.91/scripts/addons/MB-Lab/morphengine.py", line 250, in calculate_measures
    measures[measure_name] = self.calculate_measures(measure_name, vert_coords)
  File "/home/jaggz/.config/blender/2.91/scripts/addons/MB-Lab/morphengine.py", line 247, in calculate_measures
    return algorithms.length_of_strip(vert_coords, indices, axis) #check algorithms.py
  File "/home/jaggz/.config/blender/2.91/scripts/addons/MB-Lab/algorithms.py", line 86, in length_of_strip
    v1 = vertices_coords[indices[x]]
IndexError: list index out of range
```

**Comment by Upliner** [comment]
Does character creation on empty scene works well? If yes, can you please send a blend file with "offending" character only?

**Comment by jaggzh** [comment]
Hi, thanks a lot.
Okay, so a fresh blend lets me create one or more characters.
To reproduce the error with this .blend:
https://pasteall.org/blend/5b98b8dc5b6c4b59913bd63c69df0ff5

1. Load (accept or ignore the driver execution -- it's just a python scaling of text objects)
2. Finalize current char ("Finalize with textures and backup" button), accepting the automatic .png name
3. After finalization is done, click Create Character.

```
location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "/home/jaggz/.config/blender/2.91/scripts/addons/MB-Lab/__init__.py", line 2492, in execute
    start_lab_session()
  File "/home/jaggz/.config/blender/2.91/scripts/addons/MB-Lab/__init__.py", line 159, in start_lab_session
    mblab_humanoid.init_database(obj, character_identifier, rigging_type)
  File "/home/jaggz/.config/blender/2.91/scripts/addons/MB-Lab/humanoid.py", line 276, in init_database
    self.morph_engine = morphengine.MorphingEngine(self.obj_name, self.characters_config[character_identifier])
  File "/home/jaggz/.config/blender/2.91/scripts/addons/MB-Lab/morphengine.py", line 157, in __init__
    self.measures = self.calculate_measures()
  File "/home/jaggz/.config/blender/2.91/scripts/addons/MB-Lab/morphengine.py", line 250, in calculate_measures
    measures[measure_name] = self.calculate_measures(measure_name, vert_coords)
  File "/home/jaggz/.config/blender/2.91/scripts/addons/MB-Lab/morphengine.py", line 247, in calculate_measures
    return algorithms.length_of_strip(vert_coords, indices, axis) #check algorithms.py
  File "/home/jaggz/.config/blender/2.91/scripts/addons/MB-Lab/algorithms.py", line 86, in length_of_strip
    v1 = vertices_coords[indices[x]]
IndexError: list index out of range

location: <unknown location>:-1
```

**Comment by Upliner** [comment]
OK here's patch to fix it:
https://github.com/Upliner/MB-Lab/commit/c60270a5481462f927b1c837be1bb3b50c3cfecd

**Comment by Upliner** [comment]
@jaggzh also if you don't want to patch MB-Lab you can just workaround the problem by just deleting all manuellab_* properties from decimated version of the character (f_ca01.001)
![mblab1](https://user-images.githubusercontent.com/180094/110937543-2dd25400-833b-11eb-9925-36c78fe4c84e.png)

**Comment by jaggzh** [comment]
Thank you!  It's good to know the different methods.
I can probably handle patching the thing, or just checking it out from
github if it's committed.
Thanks again, I'll try to try it soon. :)

**Comment by animate1978** [comment]
I have applied the patch to the dev branch now
