### ISSUE TITLE
blender 2.93 bug

### ISSUE THREAD

**Issue by kissmecomix** [animate1978/MB-Lab#348]
**Describe the bug**

**To Reproduce**
1. Go to '...' finalize 
2. Click on '....'finalize

**Expected behavior**

**Screenshots**

**Additional context**

**Logs**
`To format it correctly, logs should go in between these:`

location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "C:\Users\rod jenkins\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\MB-Lab\__init__.py", line 1369, in execute
    mblab_humanoid.set_rest_pose()
  File "C:\Users\rod jenkins\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\MB-Lab\humanoid.py", line 1194, in set_rest_pose
    self.sk_engine.apply_armature_modifier()
  File "C:\Users\rod jenkins\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\MB-Lab\skeletonengine.py", line 119, in apply_armature_modifier
    algorithms.apply_modifier(obj, armature_modifier)
  File "C:\Users\rod jenkins\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\MB-Lab\algorithms.py", line 1142, in apply_modifier
    bpy.ops.object.modifier_apply(apply_as='DATA', modifier=modifier_name)
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\modules\bpy\ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
TypeError: Converting py args to operator properties: : keyword "apply_as" unrecognized

location: <unknown location>:-1

**Comment by animate1978** [comment]
Hello, sorry for the delay but the bug you are experiencing is from an older version that has been fixed. All you need to do is download a new clone of MB-Lab 1.7.8 from either GitHub or from this link -

https://mblab.dev/download/mb-lab-1-7-8-5/

This will allow you to finalize your character.
