### ISSUE TITLE
Toon Girl looses ability to retain status on save and reload

### ISSUE THREAD

**Issue by animate1978** [animate1978/MB-Lab#351]
**Describe the bug**
With regular MB-Lab models there is the ability to save the MB-Lab model and go back to it later, with Toon Girl that ability is lost. You start over essentially.

**To Reproduce**
Create a new character in Blender 2.93
DO NOT FINALIZE
Save this character
Close Blender 2.93
Boot up Blender 2.93 again and reload the scene.

**Expected behavior**
The model should stay in the character editing mode as it was last saved.

**Screenshots**

**Additional context**

**Logs**
`  Version 293 sub 20 date 2021-06-02 11:21 hash 84da05a8b806
Traceback (most recent call last):
  File "/home/farishta/blender-2.93.0-stable+blender-v293-release.84da05a8b806-linux.x86_64-release/2.93/scripts/addons/MB-Lab/__init__.py", line 218, in check_manuelbastionilab_session
    is_obj = algorithms.looking_for_humanoid_obj()
  File "/home/farishta/blender-2.93.0-stable+blender-v293-release.84da05a8b806-linux.x86_64-release/2.93/scripts/addons/MB-Lab/algorithms.py", line 373, in looking_for_humanoid_obj
    if utils.check_version(obj["manuellab_vers"]) and check_mesh(obj):
  File "/home/farishta/blender-2.93.0-stable+blender-v293-release.84da05a8b806-linux.x86_64-release/2.93/scripts/addons/MB-Lab/algorithms.py", line 338, in check_mesh
    logger.debug("check_obj %s model %s is not found", obj.name, obj.obj.get("manuellab_id"))
AttributeError: 'Object' object has no attribute 'obj'`
Replace the text here with your logs. To turn on the console in Blender 2.80 go to Window>Toggle System Console.

**Comment by animate1978** [comment]
This seems to be an issue ONLY with Toon Girl
