### ISSUE TITLE
Cannot install 1.8.0 to Blender 4.0

### ISSUE THREAD

**Issue by caleb-artifact** [animate1978/MB-Lab#402]
**Describe the bug**
Can't enable 1.8.0 after installing to Blender 4.0.

**To Reproduce**
1. Download the 1.8.0 release from the Github page.
2. Go to Edit > Preferences > Add-ons
3. Click on 'Install...'
4. Navigate to an select the `ML-Lab-1.8.0.zip`
5. Click on the check box to enable the extension.
6. See error

**Expected behavior**
The extension is able to load.

**Additional context**
MB-Lab version: 1.8.0
Blender Version: 4.0.2
Blender hash: 9be62e85b727

**Logs**
```
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/4.0/scripts/modules/addon_utils.py", line 364, in enable
    mod = importlib.import_module(module_name)
  File "/Applications/Blender.app/Contents/Resources/4.0/python/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'MB-Lab-1'
```

**Comment by caleb-artifact** [comment]
Well, I found the solution in the Wiki eventually. Wondering if instead of relying on the "source code" option for the release if it might be better to upload your own .zip for the release with the properly named folder inside.

**Comment by animate1978** [comment]
Yeah I made this mistake before, I did not even remember that this would happen.
