### ISSUE TITLE
KeyError: roughness

### ISSUE THREAD

**Issue by ecations** [animate1978/MB-Lab#403]
**Describe the bug**
I get a keyError when trying to finalize a character in Blender 4.0, using mblab 1.8.

**To Reproduce**
1. Create a character
2. Click on Finalize character and save to desktop.
3. Look at system console
4. See this error:
Character updated in 0.10611104965209961 secs
Warning: Cannot move modifier beyond the start of the list
Traceback (most recent call last):
  File "C:\Users\myusername\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\MBLab\__init__.py", line 1712, in execute
    mblab_humanoid.save_all_textures(self.filepath)
  File "C:\Users\myusername\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\MBLab\humanoid.py", line 532, in save_all_textures
    self.mat_engine.save_texture(new_filepath, target)
  File "C:\Users\myusername\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\MBLab\materialengine.py", line 337, in save_texture
    img_name = self.image_file_names[shader_target]
KeyError: 'roughness'

**Expected behavior**
Finalization should work.

**Comment by animate1978** [comment]
The most recent commit to the 4_0_dev_branch has fixed this bug

**Comment by animate1978** [comment]
This has been committed to the master branch as well.
